/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProspectusLead = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const InquirySubmission = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'schoolName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllLeads' : IDL.Func([], [IDL.Vec(ProspectusLead)], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(InquirySubmission)], ['query']),
  'setAdmin' : IDL.Func([IDL.Principal], [], []),
  'submitInquiry' : IDL.Func([InquirySubmission], [], []),
  'submitLead' : IDL.Func([ProspectusLead], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProspectusLead = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const InquirySubmission = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'schoolName' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllLeads' : IDL.Func([], [IDL.Vec(ProspectusLead)], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(InquirySubmission)], ['query']),
    'setAdmin' : IDL.Func([IDL.Principal], [], []),
    'submitInquiry' : IDL.Func([InquirySubmission], [], []),
    'submitLead' : IDL.Func([ProspectusLead], [], []),
  });
};

export const init = ({ IDL }) => { return []; };